Fix: #333 Fix the created hook in page is wrongly called when layout changes
ktsn/vue-router-layout pull request #334
Opened 2021-08-29 07:10 UTC by Azurewarth0920

Fix: #333 
Check the current layout and resolved the layout component can prevent unnecessary render.

2022-01-04 12:36 UTC, Azurewarth0920 commented
@ktsn 
Would you like to take a look at this PR?

2022-01-10 01:23 UTC, ktsn requested changes
Can you add a test case for this?

2022-01-23 14:29 UTC, Azurewarth0920 commented
@ktsn 
Added a test here: https://github.com/ktsn/vue-router-layout/pull/334/commits/a04a21b4c6f20970c8a0d70b203c3347281c2a9e

Can you review it?.

2022-01-31 05:04 UTC, ktsn approved these changes
Thank you!

2022-01-31 05:04 UTC, merged